### ISSUE TITLE
Integration of OpenAPI specification or document for vulnerable endpoints.

### ISSUE THREAD

**Issue by SyCode7** [snoopythesecuritydog/dvws#6]
Thanks for this very useful tool. I will like to recommend integration of a feature.
Since there is already a WADL component, how about defining a document that contains the vulnerable endpoints in DVWS ? A possible standard could be using the [Open API](https://github.com/OAI/OpenAPI-Specification) (formerly Swagger). The OpenAPI is getting popular and its inclusion could be a very useful functionality for REST security testing. Cheers !

**Comment by snoopysecurity** [comment]
Definitely a good idea! Will try and implement this in the coming months after a couple of feature releases.

**Comment by SyCode7** [comment]
Thanks a lot for your quick response.
