### ISSUE TITLE
REST API SQL Injection is broken

### ISSUE THREAD

**Issue by vishrantkhanna** [snoopythesecuritydog/dvws#7]
REST API SQL Injection is broken. 
When "/dvws/vulnerabilities/sqli/api.php/users/2" is called it returns "Fatal error: Uncaught Error: Call to undefined function mysql_connect()"

**Comment by snoopysecurity** [comment]
Hey! just a note that this project is out of date, please use https://github.com/snoopysecurity/dvws-node
