### ISSUE TITLE
The code is written with older version of PHP. Below is the edit api.php

### ISSUE THREAD

**Issue by Le4kno3** [snoopythesecuritydog/dvws#8]
[api.zip](https://github.com/snoopysecurity/dvws/files/6076897/api.zip)

**Comment by snoopysecurity** [comment]
Hi, no problem @JLeLo, i've made the change https://github.com/snoopysecurity/dvws/commit/5fc2ed8f1860067038efbc2a8993c9932e0edc6e. Also this project isn't supported anymore, i've migrated most of the codebase to node. The node version can be seen here: https://github.com/snoopysecurity/dvws-node
